version: '3'
services:
    app:
        image: node:8.1.2
        entrypoint: npm
        command: start
        working_dir: /workspace
        volumes:
            - .:/workspace
        ports:
            - 3000:3000
