version: '3'
services:
    app:
        image: node:7.9.0
        entrypoint: npm
        command: start
        working_dir: /workspace
        volumes:
            - .:/workspace
        ports:
            - 3000:3000
